### ISSUE TITLE
Windows does not allow : in filenames

### ISSUE THREAD

**Issue by robinflyhigh** [ramoneg/scraper#1]
if (file_put_contents(dirname(__FILE__) . "/exports/" . date("Y-m-d H:i") . ".json", $json)) {

should be

if (file_put_contents(dirname(__FILE__) . "/exports/" . date("Y-m-d H-i") . ".json", $json)) {

**Comment by ramoneg** [comment]
I just released v1.1.3. You can run composer update.
Thank you!
